name: Repro devenv 2059

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ver: [ "v1.8.1", "main" ]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - name: Install devenv
        run: |
          set -x
          nix profile install --accept-flake-config github:cachix/devenv/${{ matrix.ver }}
      - name: Step 1, should have wazzup command
        run: |
          set -x
          log=output.log
          cp -r steps/step1/* .
          echo 'should echo "YO wazzup"'
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
      - name: Step 2, should still have wazzup plus a new derivation testderiv2
        run: |
          set -x
          log=output2.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step2/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv2"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv2" $log || exit 1
      - name: Step 3, same as 2, except should recognize devenv.local.nix
        run: |
          set -x
          log=output3.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step3/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv2"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv2" $log || exit 1
          echo
          echo 'should echo "XXX yeah has devenv local XXX"'
          echo
          devenv shell hasdevenvlocal 2>&1 | tee -a $log
          grep -q "XXX yeah has devenv local XXX" $log || exit 1
      - name: Step 4, same as 3, except devenv.local.nix removed
        run: |
          set -x
          log=output4.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step4/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv2"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv2" $log || exit 1
          echo
          echo 'should echo "XXX  XXX"'
          echo
          devenv shell hasdevenvlocal 2>&1 | tee -a $log
          grep -q "XXX  XXX" $log || exit 1
      - name: Step 5, same as 4, except testderiv2 replaced by testderiv3
        run: |
          set -x
          log=output5.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step5/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv3"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv3" $log || exit 1
          echo
          echo 'should echo "XXX  XXX"'
          echo
          devenv shell hasdevenvlocal 2>&1 | tee -a $log
          grep -q "XXX  XXX" $log || exit 1
      - name: Step 6, same as 5, except testderiv3 replaced by testderiv4 and impure
        run: |
          set -x
          log=output6.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step6/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv4"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv4" $log || exit 1
          echo
          echo 'should echo "XXX  XXX"'
          echo
          devenv shell hasdevenvlocal 2>&1 | tee -a $log
          grep -q "XXX  XXX" $log || exit 1
      - name: Step 7, same as 6, except testderiv4 replaced by testderiv3 and pure
        run: |
          set -x
          log=output7.log
          rm -f devenv.nix devenv.local.nix
          cp -r steps/step7/* .
          echo
          echo 'should echo "YO wazzup"'
          echo
          devenv shell wazzup 2>&1 | tee $log
          grep -q "YO wazzup" $log || exit 1
          echo
          echo 'should echo "YO from testderiv3"'
          echo
          devenv shell testderiv 2>&1 | tee -a $log
          grep -q "YO from testderiv3" $log || exit 1
          echo
          echo 'should echo "XXX  XXX"'
          echo
          devenv shell hasdevenvlocal 2>&1 | tee -a $log
          grep -q "XXX  XXX" $log || exit 1
